### ISSUE TITLE
Failed to install Nvidia Driver for Realtime Kernel.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#13260]
On Ubuntu 20.10, I compiled and installed the Realtime-rt_preempt-kernel according to the [guidance](https://index.ros.org/doc/ros2/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2/). But failed to install Nvidia Driver for Realtime Kernel following the [instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md#install-nvidia-driver-for-realtime-kernel). See following for more info:

```
$ cd $( dpkg --get-selections | grep ^nvidia-kernel-source | awk '{print $1}' | xargs dpkg -L | grep -m1 "nvidia-drm" | xargs dirname )

$ sudo env NV_VERBOSE=1     make -j8 NV_EXCLUDE_BUILD_MODULES=''     KERNEL_UNAME=$(uname -r)     IGNORE_XEN_PRESENCE=1     IGNORE_CC_MISMATCH=1     IGNORE_PREEMPT_RT_PRESENCE=1     SYSSRC=/lib/modules/$(uname -r)/build     LD=/usr/bin/ld.bfd     modules

[...]
In file included from /usr/src/nvidia-455.45.01/nvidia/nv.c:14:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/src/nvidia-455.45.01/nvidia/nv-acpi.c:15:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/src/nvidia-455.45.01/nvidia/nv-dma.c:15:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/src/nvidia-455.45.01/nvidia/nv-frontend.c:13:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/src/nvidia-455.45.01/nvidia/nv-cray.c:15:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-acpi.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv.o] Error 1
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-dma.o] Error 1
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-frontend.o] Error 1
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-cray.o] Error 1
In file included from /usr/src/nvidia-455.45.01/common/inc/nv-pci.h:15,
                 from /usr/src/nvidia-455.45.01/nvidia/nv-pci.c:13:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-pci.o] Error 1
In file included from /usr/src/nvidia-455.45.01/nvidia/nv-mmap.c:15:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/src/nvidia-455.45.01/nvidia/nv-i2c.c:17:
/usr/src/nvidia-455.45.01/common/inc/nv-linux.h:119:10: fatal error: asm/kmap_types.h: No such file or directory
  119 | #include <asm/kmap_types.h>         /* page table entry lookup          */
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-mmap.o] Error 1
make[2]: *** [scripts/Makefile.build:279: /usr/src/nvidia-455.45.01/nvidia/nv-i2c.o] Error 1
make[1]: *** [Makefile:1805: /usr/src/nvidia-455.45.01] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.1-rt20'
make: *** [Makefile:81: modules] Error 2
```
The self compiled and installed RT kernel info is shown below:
```
$ uname -r
5.10.1-rt20
```
Any hints for solving this problem?

Best,
HY

**Comment by storypku** [comment]
Nope. We would provide support for how to install Nvidia drivers on non-LTS Ubuntu kernels. And This issue is going to be closed. You can ask for help from Nvidia or Ubuntu community though.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your notes. It works on Ubuntu 20.04 LTS. See the following for more detailed info:

```
werner@X10DAi:~/Desktop$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
werner@X10DAi:~/Desktop$ uname -r
5.4.84-rt47
werner@X10DAi:~/Desktop$ nvidia-smi
Thu Dec 31 17:44:16 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  On   | 00000000:02:00.0  On |                  N/A |
|  0%   33C    P8    22W / 215W |    185MiB /  7977MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2166      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      2661      G   /usr/lib/xorg/Xorg                 86MiB |
|    0   N/A  N/A     12618      G   /usr/bin/gnome-shell               51MiB |
+-----------------------------------------------------------------------------+
```
